#include <string>
#include <schemeobject.h>
#include <sstream>
#include <parser.h>

const std::string startup = "(define (> x y) (< y x)) "
        "(define (>= x y) (not (< x y))) "
        "(define (<= x y) (not (< y x))) "
        "(define true #t) "
        "(define false #f) "
        "(define (not x) (if x #f #t)) "
        "(define (abs x) (if (< x 0) (- x) x)) "
        "(define (positive? x) (> x 0)) "
        "(define (negative? x) (< x 0)) "
        "(define (zero? x) (= x 0)) "
        "(define (list . x) x) "
        "(define nil (list)) "
        "(define (newline) (display \"\\n\")) "
        "(define (min a . l)"
        "  (define (min-iter a l)"
        "    (cond ((null? l) a) ((< a (car l)) (min-iter a (cdr l))) (else (min-iter (car l) (cdr l)))))"
        "  (min-iter a l)) "
        "(define (max a . l)"
        "  (define (max-iter a l)"
        "    (cond ((null? l) a) ((< (car l) a) (max-iter a (cdr l))) (else (max-iter (car l) (cdr l)))))"
        "  (max-iter a l)) "
        "(define (map fun . args)"
        "  (define (cars l) (if (null? l) nil (cons (car (car l)) (cars (cdr l)))))"
        "  (define (cdrs l) (if (null? l) nil (cons (cdr (car l)) (cdrs (cdr l)))))"
        "  (define (nils l) (and (not (null? l)) (or (null? (car l)) (nils (cdr l)))))"
        "  (if (or (null? args) (nils args)) nil (cons (apply fun (cars args)) (apply map fun (cdrs args))))) "
        "(define (for-each fun . args)"
        "  (define (cars l) (if (null? l) nil (cons (car (car l)) (cars (cdr l)))))"
        "  (define (cdrs l) (if (null? l) nil (cons (cdr (car l)) (cdrs (cdr l)))))"
        "  (define (nils l) (and (not (null? l)) (or (null? (car l)) (nils (cdr l)))))"
        "  (cond ((or (null? args) (nils args)) \"\") (else (apply fun (cars args)) (apply for-each fun (cdrs args))))) "
        "(define (length l)"
        "  (define (length-iter l c) (if (null? l) c (length-iter (cdr l) (+ c 1))))"
        "  (length-iter l 0)) "
        "(define (append . x)"
        "  (define (f x y) (if (null? x) y (cons (car x) (f (cdr x) y))))"
        "  (fold-right f nil x)) "
        "(define (even? x) (= 0 (remainder x 2))) "
        "(define (odd? x) (not (even? x))) "
        "(define (filter predicate sequence)"
        "  (cond ((null? sequence) nil) ((predicate (car sequence)) (cons (car sequence)"
        "  (filter predicate (cdr sequence)))) (else (filter predicate (cdr sequence))))) "
        "(define (fold-right op initial sequence)"
        "  (if (null? sequence) initial (op (car sequence) (fold-right op initial (cdr sequence))))) "
        "(define (fold-left op initial sequence)"
        "  (define (iter result rest) (if (null? rest) result (iter (op result (car rest))"
        "  (cdr rest)))) (iter initial sequence)) "
        "(define (reverse items)"
        "  (fold-left (lambda (x y) (cons y x)) nil items)) "
        "(define (null? x) (eq? x nil)) "
        "(define (equal? a b)"
        "  (cond ((and (pair? a) (pair? b)) (and (equal? (car a) (car b)) (equal? (cdr a) (cdr b))))"
        "    ((and (string? a) (string? b)) (string=? a b))"
        "    (else (eq? a b)))) "
        "(define (gcd a b) (if (= b 0) a (gcd b (remainder a b)))) "
        "(define (last-pair x) (if (pair? (cdr x)) (last-pair (cdr x)) x)) "
        "(define (append! x . y)"
        "  (define (f x y) (set-cdr! (last-pair x) y) x)"
        "  (if (null? y) x (f x (apply append! y)))) "
        "(define stream-car car) "
        "(define (stream-cdr x) (force (cdr x))) "
        "(define stream-null? null?) "
        "(define the-empty-stream nil) "
        "(define (stream-map fun . args)"
        "  (define (cars l) (if (null? l) nil (cons (stream-car (car l)) (cars (cdr l)))))"
        "  (define (cdrs l) (if (null? l) nil (cons (stream-cdr (car l)) (cdrs (cdr l)))))"
        "  (define (nils l) (and (not (null? l)) (or (stream-null? (car l)) (nils (cdr l)))))"
        "  (if (or (null? args) (nils args)) the-empty-stream (cons-stream (apply fun (cars args)) (apply stream-map fun (cdrs args))))) "
        "(define (stream-ref stream k) (if (= k 0) (stream-car stream) (stream-ref (stream-cdr stream) (- k 1)))) "
        "(define (stream-head stream k) (if (= k 0) nil (cons (stream-car stream) (stream-head (stream-cdr stream) (- k 1))))) "
        "(define system-global-environment (the-environment)) "
        "(define (member-procedure eq) (define (fun object list) "
        "  (cond ((null? list) false) ((eq object (car list)) list) (else (fun object (cdr list))))) fun) "
        "(define memq (member-procedure eq?)) "
        "(define member (member-procedure equal?)) "
        "(define eqv? eq?) "
        "(define real? number?) "
        "(define (integer? x) (and (number? x) (= x (round x)))) "
        "(define (inexact? x) (and (number? x) (not (exact? x)))) "
        "(define exact-integer? exact?)"
        "(define (exact-nonnegative-integer? x) (and (exact? x) (>= x 0))) "
        "(define (1+ x) (+ 1 x)) "
        "(define (-1+ x) (- x 1)) "
        "(define (expt x y) (exp (* y (log x)))) "
        "(define char=? eq?) "
        "(define (char<? a b) (< (char->integer a) (char->integer b))) "
        "(define (char>? a b) (char<? b a)) "
        "(define (char<=? a b) (or (char<? a b) (char=? a b))) "
        "(define (char>=? a b) (or (char>? a b) (char=? a b))) "
        "(define (char-ci=? a b) (char=? (char-downcase a) (char-downcase b))) "
        "(define (char-ci<? a b) (char<? (char-downcase a) (char-downcase b))) "
        "(define (char-ci>? a b) (char-ci<? b a)) "
        "(define (char-ci<=? a b) (or (char-ci<? a b) (char-ci=? a b))) "
        "(define (char-ci>=? a b) (or (char-ci>? a b) (char-ci=? a b))) "
        "(define char-code char->integer) "
        "(define char-ascii? char?) "
        "(define char->ascii char->integer) "
        "(define ascii->char integer->char) "
        "(define (list->string l) (apply string l)) "
        "(define (string-null? s) (eq? s \"\")) "
        "(define (string-copy s) (string-append s)) "
        "(define (string-head s e) (substring s 0 e)) "
        "(define (string-tail s b) (substring s b (string-length s))) "
        "(define (substring-downcase! s a b) "
        "  (do ((i a (1+ i))) ((= i b)) (string-set! s i (char-downcase (string-ref s i)))) s) "
        "(define (substring-upcase! s a b) "
        "  (do ((i a (1+ i))) ((= i b)) (string-set! s i (char-upcase (string-ref s i)))) s) "
        "(define (string-downcase! s) (substring-downcase! s 0 (string-length s))) "
        "(define (string-upcase! s) (substring-upcase! s 0 (string-length s))) "
        "(define (string-downcase s) (string-downcase! (string-copy s))) "
        "(define (string-upcase s) (string-upcase! (string-copy s))) "
        "(define (string-upper-case? s) (and (> (string-length s) 0) (string=? s (string-upcase s)))) "
        "(define (string-lower-case? s) (and (> (string-length s) 0) (string=? s (string-downcase s))))"
        "(define (substring-upper-case? s a b) (string-upper-case? (substring s a b))) "
        "(define (substring-lower-case? s a b) (string-lower-case? (substring s a b))) "
        "(define (substring=? s1 a1 b1 s2 a2 b2) (string=? (substring s1 a1 b1) (substring s2 a2 b2))) "
        "(define (string-ci=? s t) (string=? (string-downcase s) (string-downcase t))) "
        "(define (substring-ci=? s1 a1 b1 s2 a2 b2) (string-ci=? (substring s1 a1 b1) (substring s2 a2 b2))) "
        "(define (substring<? s1 a1 b1 s2 a2 b2) (string<? (substring s1 a1 b1) (substring s2 a2 b2))) "
        "(define (string>? a b) (string<? b a)) "
        "(define (string<=? a b) (or (string<? a b) (string=? a b))) "
        "(define (string>=? a b) (or (string>? a b) (string=? a b))) "
        "(define (string-ci<? a b) (string<? (string-downcase a) (string-downcase b)))"
        "(define (substring-ci<? s1 a1 b1 s2 a2 b2) (string-ci<? (substring s1 a1 b1) (substring s2 a2 b2)))"
        "(define (string-ci>? a b) (string-ci<? b a)) "
        "(define (string-ci<=? a b) (or (string-ci<? a b) (string-ci=? a b))) "
        "(define (string-ci>=? a b) (or (string-ci>? a b) (string-ci=? a b))) "
        "(define (substring-search-forward p s a b) "
        "  (let ((res (string-search-forward p (substring s a b)))) (if res (+ res a) res))) "
        "(define (substring-search-backward p s a b) "
        "  (let ((res (string-search-backward p (substring s a b)))) (if res (+ res a) res))) "
        "(define (substring-search-all p s a b) "
        "  (map (lambda (x) (+ x a)) (string-search-all p (substring s a b)))) "
        "(define (substring? p s) (number? (string-search-forward p s))) "
        "(define (string-find-next-char s c) (string-search-forward (string c) s)) "
        "(define (substring-find-next-char s a b c) (substring-search-forward (string c) s a b)) "
        "(define (string-find-next-char-ci s c) "
        "  (string-find-next-char (string-downcase s) (char-downcase c))) "
        "(define (substring-find-next-char-ci s a b c) "
        "  (substring-find-next-char (string-downcase s) a b (char-downcase c))) "
        "(define (string-find-previous-char s c) "
        "  (let ((res (string-search-backward (string c) s))) (if res (- res 1) res))) "
        "(define (substring-find-previous-char s a b c) "
        "  (let ((res (substring-search-backward (string c) s a b))) (if res (- res 1) res))) "
        "(define (string-find-previous-char-ci s c) "
        "  (string-find-previous-char (string-downcase s) (char-downcase c))) "
        "(define (substring-find-previous-char-ci s a b c) "
        "  (substring-find-previous-char (string-downcase s) a b (char-downcase c))) "
        "(define (substring-match-forward s1 a1 b1 s2 a2 b2) "
        "  (string-match-forward (substring s1 a1 b1) (substring s2 a2 b2))) "
        "(define (string-match-forward-ci s t) (string-match-forward (string-downcase s) (string-downcase t))) "
        "(define (substring-match-forward-ci s1 a1 b1 s2 a2 b2) "
        "  (string-match-forward-ci (substring s1 a1 b1) (substring s2 a2 b2))) "
        "(define (substring-match-backward s1 a1 b1 s2 a2 b2) "
        "  (string-match-backkward (substring s1 a1 b1) (substring s2 a2 b2))) "
        "(define (string-match-backward-ci s t) (string-match-backward (string-downcase s) (string-downcase t))) "
        "(define (substring-match-backward-ci s1 a1 b1 s2 a2 b2) "
        "  (string-match-backward-ci (substring s1 a1 b1) (substring s2 a2 b2))) "
        "(define (string-prefix? s t) (= (string-match-forward s t) (string-length s))) "
        "(define (substring-prefix? s1 a1 b1 s2 a2 b2) "
        "  (string-prefix? (substring s1 a1 b1) (substring s2 a2 b2))) "
        "(define (string-prefix-ci? s t) (string-prefix? (string-downcase s) (string-downcase t))) "
        "(define (substring-prefix-ci? s1 a1 b1 s2 a2 b2) "
        "  (string-prefix-ci? (substring s1 a1 b1) (substring s2 a2 b2))) "
        "(define (string-suffix? s t) (= (string-match-backward s t) (string-length s))) "
        "(define (substring-suffix? s1 a1 b1 s2 a2 b2) "
        "  (string-suffix? (substring s1 a1 b1) (substring s2 a2 b2))) "
        "(define (string-suffix-ci? s t) (string-suffix? (string-downcase s) (string-downcase t))) "
        "(define (substring-suffix-ci? s1 a1 b1 s2 a2 b2) "
        "  (string-suffix-ci? (substring s1 a1 b1) (substring s2 a2 b2))) "
        ;


Context initGlobalContext()
{
    Context global_context;
    global_context.newFrame();
    std::istringstream st;
    st.str(startup);
    std::shared_ptr<ASTNode> x;
    while(1)
    {
        try
        {
            x = readObject(st);
            x->evaluate(global_context);
        }
        catch(end_of_input)
        {
            break;
        }
    }
    global_context.newFrame();
    global_context.set("user-initial-environment", std::make_shared<SchemeEnvironment>(global_context));
    return global_context;
}
