#include <string>

std::string startup = "(define (> x y) (< y x)) "
        "(define true (< 0 1)) "
        "(define false (< 1 0)) "
        "(define (not x) (if x false true)) "
        "(define (abs x) (if (< x 0) (- x) x)) "
        "(define (positive? x) (> x 0)) "
        "(define (negative? x) (< x 0)) "
        "(define (list . x) x) "
        "(define nil (list)) "
        "(define (newline) (display \"\n\")) "
        "(define (min a . l)"
        "  (define (min-iter a l)"
        "    (cond ((null? l) a) ((< a (car l)) (min-iter a (cdr l))) (else (min-iter (car l) (cdr l)))))"
        "  (min-iter a l)) "
        "(define (max a . l)"
        "  (define (max-iter a l)"
        "    (cond ((null? l) a) ((< (car l) a) (max-iter a (cdr l))) (else (max-iter (car l) (cdr l)))))"
        "  (max-iter a l)) "
        "(define (map fun . args)"
        "  (define (cars l) (if (null? l) nil (cons (car (car l)) (cars (cdr l)))))"
        "  (define (cdrs l) (if (null? l) nil (cons (cdr (car l)) (cdrs (cdr l)))))"
        "  (define (nils l) (and (not (null? l)) (or (null? (car l)) (nils (cdr l)))))"
        "  (if (or (null? args) (nils args)) nil (cons (apply fun (cars args)) (apply map fun (cdrs args))))) "
        "(define (for-each fun . args)"
        "  (define (cars l) (if (null? l) nil (cons (car (car l)) (cars (cdr l)))))"
        "  (define (cdrs l) (if (null? l) nil (cons (cdr (car l)) (cdrs (cdr l)))))"
        "  (define (nils l) (and (not (null? l)) (or (null? (car l)) (nils (cdr l)))))"
        "  (cond ((or (null? args) (nils args)) \"\") (else (apply fun (cars args)) (apply for-each fun (cdrs args))))) "
        "(define (length l)"
        "  (define (length-iter l c) (if (null? l) c (length-iter (cdr l) (+ c 1))))"
        "  (length-iter l 0)) "
        "(define (append list1 list2)"
        "  (if (null? list1) list2 (cons (car list1) (append (cdr list1) list2)))) "
        "(define (even? x) (= 0 (remainder x 2))) "
        "(define (odd? x) (not (even? x))) "
        "(define (filter predicate sequence)"
        "  (cond ((null? sequence) nil) ((predicate (car sequence)) (cons (car sequence)"
        "  (filter predicate (cdr sequence)))) (else (filter predicate (cdr sequence))))) "
        "(define (fold-right op initial sequence)"
        "  (if (null? sequence) initial (op (car sequence) (fold-right op initial (cdr sequence))))) "
        "(define (fold-left op initial sequence)"
        "  (define (iter result rest) (if (null? rest) result (iter (op result (car rest))"
        "  (cdr rest)))) (iter initial sequence)) "
        "(define (reverse items)"
        "  (fold-left (lambda (x y) (cons y x)) nil items)) "
        "(define (null? x) (eq? x nil)) ";
